create table if not exists public.scans (
	id bigint generated by default as identity primary key,
	patient_id text not null,
	timestamp timestamptz not null default now(),
	original_image_url text not null,
	heatmap_image_url text not null,
	diagnosis text not null,
	severity text not null,
	confidence integer not null,
	model_version text not null,
	inference_mode text not null,
	inference_time integer not null,
	preprocessing_method text not null,
	metadata jsonb
);

create index if not exists scans_patient_id_idx on public.scans (patient_id);
create index if not exists scans_timestamp_idx on public.scans (timestamp desc);

alter table public.scans enable row level security;

create policy "Service role full access" on public.scans
	using (auth.role() = 'service_role')
	with check (auth.role() = 'service_role');
